[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "motioneye"
dynamic = ["version"]
dependencies = [
  "tornado>=6.5.8",
  "jinja2",
  "pillow",
  "pycurl",
  "babel",
  "boto3",
  "argon2-cffi",
]
requires-python = ">=3.7"
authors = [
  {name = "Calin Crisan", email = "ccrisan@gmail.com"},
  {name = "Jean Michault"},
]
maintainers = [
  {name = "MichaIng", email = "micha@dietpi.com"},
]
description = "motioneye, a multilingual web interface for motion."
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
keywords = ["motion", "video", "surveillance", "frontend"]
classifiers = [
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3",
  "Topic :: Multimedia :: Video :: Capture",
]

[project.urls]
Homepage = "https://github.com/motioneye-project/motioneye"
Source = "https://github.com/motioneye-project/motioneye"
Changelog = "https://github.com/motioneye-project/motioneye/releases"
Issue = "https://github.com/motioneye-project/motioneye/issues"

[project.scripts]
meyectl = "motioneye.meyectl:main"
motioneye_init = "motioneye.motioneye_init:main"

[tool.setuptools]
packages = ["motioneye"]
include-package-data = false

[tool.setuptools.package-data]
motioneye = ["extra/*", "static/*.*", "static/*/*", "templates/*", "scripts/*", "controls/*", "handlers/*", "utils/*", "locale/*/LC_MESSAGES/*.mo"]

[tool.setuptools.dynamic]
version = {attr = "motioneye.VERSION"}

[tool.bandit]
# skip hardcoded password, MD5/SHA1 hashes, import subprocess, subprocess.run(..., shell=False)
skips = ["B105", "B324", "B404", "B603"]

[tool.black]
skip-string-normalization = true
target-version = ["py37", "py38", "py39", "py310", "py311", "py312", "py313", "py314", "py315"]

[tool.codespell]
ignore-words-list = "ot"
skip = "*.html,*.js,*.json,*.po,*.pot"

[tool.flake8]
builtins = ["_"]
count = true
max-complexity = 68
max-line-length = 125
# flake8-return rules to add after its next release: https://github.com/afonasev/flake8-return/pull/139
# => R501,R502,R503,R504,R505,R506,R507,R508
select = ["C901", "E501", "E9", "F63", "F7", "F82"]
show-source = true
statistics = true

[tool.isort]
profile = "black"

[tool.pyupgrade]
py37-plus = true

[tool.ruff]
builtins = ["_"]
target-version = "py37"

[tool.ruff.format]
quote-style = "preserve"

[tool.ruff.lint]
ignore = ["E722", "LOG015", "BLE001"]
