version: "3.5"
services:
  motioneye:
    restart: unless-stopped
    image: ccrisan/motioneye:dev-amd64  # dev image
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    volumes:
      - /etc/localtime:/etc/localtime:ro
