name: lint_legacy_python
on: [pull_request, push]
jobs:
   lint_legacy_python:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-python@v3
         with:
           python-version: 2.7
       - run: sudo apt upgrade -y && sudo apt-get install curl ffmpeg libcurl4-openssl-dev libssl-dev motion ssh v4l-utils -y 
       - run: pip install --upgrade pip wheel
       - run: pip install codespell flake8 flake8-comprehensions pytest
       - run: codespell --ignore-words-list="files',ot,process'" --skip="./.*,*.eod,*.gif,*.png,*.ttf,*.woff"
       - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
       - run: flake8 . --count --exit-zero --max-complexity=12 --max-line-length=125
                       --show-source --statistics
       - run: pip install -r requirements.txt
       - run: pip install pycurl || true  # 7.43.0.5 fails on legacy Python!
       # - run: pip install pycurl==7.44.1 || true
       # - run: pip install pycurl==7.43.0.3 || true
       - run: pytest . || pytest --doctest-modules . || true
