name: shellcheck
on: [pull_request, push]
jobs:
  shellcheck:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.owner.login != github.event.pull_request.base.repo.owner.login
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: shellcheck --version  # https://github.com/koalaman/shellcheck/wiki/Recursiveness
      - run: |
          mapfile -t FILES < <(find . -type f) # read all files to array
          for i in "${!FILES[@]}"
          do
              [[ ${FILES[$i]} == *'.'*'sh' ]] && continue # file has shell extension
              awk 'NR==1 && $1 ~ /^#!.*sh$/' "${FILES[$i]}" && continue # file has shell shebang
              unset -v "FILES[$i]" # else remove from array
          done
          shellcheck "${!FILES[@]}" || true  # TODO: Fix all issues and remove `|| true`
