name: ubuntu_build

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.owner.login != github.event.pull_request.base.repo.owner.login
    strategy:
      matrix:
        dist: ['ubuntu-22.04', 'ubuntu-24.04', 'ubuntu-22.04-arm', 'ubuntu-24.04-arm']
      fail-fast: false
    runs-on: ${{ matrix.dist }}
    name: "Test on ${{ matrix.dist }}"
    steps:
      - if: matrix.dist == 'ubuntu-22.04' || matrix.dist == 'ubuntu-24.04'
        run: sudo apt-mark hold grub-efi-amd64-signed # GRUB does not always find the drive it was configured for
      - name: Ubuntu Noble workarounds
        if: matrix.dist == 'ubuntu-24.04' || matrix.dist == 'ubuntu-24.04-arm'
        run: |
          # https://github.com/actions/runner-images/pull/9956
          # ERROR: Cannot uninstall pip 24.0, RECORD file not found. Hint: The package was installed by debian.
          # new firefox package pre-installation script subprocess returned error exit status 1
          sudo apt-get autopurge needrestart python3-pip python3-setuptools python3-wheel firefox
          # error: externally-managed-environment
          echo -e '[global]\nbreak-system-packages=true' | sudo tee /etc/pip.conf
      - run: sudo apt-get -q update
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get -qq --no-install-recommends dist-upgrade
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get -qq --no-install-recommends install
                  ca-certificates curl gcc libcurl4-openssl-dev libssl-dev python3-dev
      - run: curl -sSfO 'https://bootstrap.pypa.io/get-pip.py'
      - run: sudo python3 get-pip.py
      - run: sudo python3 -m pip install --upgrade pip setuptools wheel
      - run: |
          REPO=$GITHUB_REPOSITORY BRANCH=$GITHUB_REF_NAME
          [ ${{ github.event_name }} = 'pull_request' ] && REPO=${{ github.event.pull_request.head.repo.full_name }} BRANCH=${{ github.event.pull_request.head.ref }}
          sudo python3 -m pip install "https://github.com/$REPO/archive/$BRANCH.tar.gz"
      - run: sudo motioneye_init --skip-apt-update
      - run: i=0; until ss -tln | grep 8765; do [ $i -le 10 ] || exit 0; sleep 1; i=$(expr $i + 1); done
      - run: sudo systemctl status motioneye
      - run: sudo systemctl is-active motioneye
