# https://github.com/motioneye-project/motioneye/wiki/%28Install-On-Ubuntu-%2820.04-or-Newer%29
name: ubuntu_build
on: [pull_request, push]
jobs:
  ubuntu_build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.owner.login != github.event.pull_request.base.repo.owner.login
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get -q update
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get -qq upgrade
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get -qq install
             libcurl4-openssl-dev libssl-dev python3-dev python3-pip
      - run: |
          REPO=$GITHUB_REPOSITORY BRANCH=$GITHUB_REF_NAME
          [ ${{ github.event_name }} = 'pull_request' ] && REPO=${{ github.event.pull_request.head.repo.full_name }} BRANCH=${{ github.event.pull_request.head.ref }}
          sudo python3 -m pip install "https://github.com/$REPO/archive/$BRANCH.tar.gz"
      - run: sudo motioneye_init
      - run: i=0; until ss -tln | grep 8765; do [ $i -le 10 ] || exit 0; sleep 1; i=$(expr $i + 1); done
      - run: sudo systemctl status motioneye
      - run: sudo systemctl is-active motioneye
