name: ubuntu_build

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.owner.login != github.event.pull_request.base.repo.owner.login
    strategy:
      matrix:
        dist: ['ubuntu-20.04', 'ubuntu-22.04']
    runs-on: ${{ matrix.dist }}
    name: "Test on ${{ matrix.dist }}"
    steps:
      - run: sudo apt-mark hold grub-efi-amd64-signed # GRUB does not always find the drive it was configured for
      - run: sudo apt-get -q update
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get -qq --no-install-recommends dist-upgrade
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get -qq --no-install-recommends install
                  ca-certificates curl gcc libcurl4-openssl-dev libssl-dev python3-dev
      - run: curl -sSfO 'https://bootstrap.pypa.io/get-pip.py'
      - run: sudo python3 get-pip.py
      - run: sudo python3 -m pip install --upgrade pip setuptools wheel
      - run: |
          REPO=$GITHUB_REPOSITORY BRANCH=$GITHUB_REF_NAME
          [ ${{ github.event_name }} = 'pull_request' ] && REPO=${{ github.event.pull_request.head.repo.full_name }} BRANCH=${{ github.event.pull_request.head.ref }}
          sudo python3 -m pip install "https://github.com/$REPO/archive/$BRANCH.tar.gz"
      - run: sudo motioneye_init --skip-apt-update
      - run: i=0; until ss -tln | grep 8765; do [ $i -le 10 ] || exit 0; sleep 1; i=$(expr $i + 1); done
      - run: sudo systemctl status motioneye
      - run: sudo systemctl is-active motioneye
