name: update_locales

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_locales:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/setup-python@v4
    - run: |
        python3 -m pip install -U babel &
        sudo apt-get -q update
        sudo DEBIAN_FRONTEND="noninteractive" apt-get -qq --no-install-recommends install make gettext
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        # https://github.com/peter-evans/create-pull-request/issues/48
        token: ${{ secrets.GH_PAT }}
    - run: |
        make
        git diff --exit-code && exit 0
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A
        git commit -m 'Update JSON locales'
        git push
